### ISSUE TITLE
Ship babelified code to NPM for the web platform

### ISSUE THREAD

**Issue by hectahertz** [hectahertz/react-native-typography#15]
Should we follow [the approach of React Navigation](https://github.com/react-navigation/react-navigation/blob/master/package.json) and ship both ES6 and babelified code on npm?

We could use the latter on the web platform and the consumers would not need to worry about Babel.

**Comment by necolas** [comment]
Yes please, that would be great :)

**Comment by gut4** [comment]
Yes it's very useful. Now if project created via [create-react-app](https://github.com/facebookincubator/create-react-app) you get an error and need manually edit configuration.

**Comment by hectahertz** [comment]
Done in v1.3.0 😄
