### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by jsp3536** [hectahertz/react-native-typography#17]
I am trying to get this library working for react-native-windows and ran into a similar problem  as the react-native-web issure where systemWeights was undefined. I got the library working by making a systemDenseWeights.windows.js, systemTallWeights.windows.js, and systemWeights.windows.js files. Is this the best ways to do this or is there another way the can be done to default the imports when Platform.OS is unknown?

**Comment by hectahertz** [comment]
Hi @jsp3536, thanks for the issue!

Yes, that would be the best way to support a new platform.

I haven't used `react-native-windows` before, and I couldn't find any docs about `fontWeight` or `fontFamily`, but it looks like part of the logic is here: https://github.com/Microsoft/react-native-windows/blob/f9230c27829edfced8b623762799c1853f169f84/ReactWindows/ReactNative.Shared/Views/Text/FontStyleHelpers.cs

If we were to officially support this then we should work on matching the values so the experience is still consistent.

If you want to work on it, we're open for PRs 😄 

Thanks again!
