### ISSUE TITLE
systemWeight black

### ISSUE THREAD

**Issue by hatemalimam** [hectahertz/react-native-typography#26]
I was wondering why the systemWeight black is not exported [here](https://github.com/hectahertz/react-native-typography/blob/master/src/helpers/systemWeights.ios.js#L8) ?

Is it because it's not available in android ? how about a fallout to bold in case of android ?

**Comment by hectahertz** [comment]
Hi @hatemalimam, that's the reason!

I think it's a good idea to only keep the styles that actually match in `systemWeights` to avoid surprises. If the consumer of the library wants that behaviour, it can be done manually.

Thanks for the suggestion!
