### ISSUE TITLE
Include material typography adjustments for tall and dense scripts

### ISSUE THREAD

**Issue by necolas** [hectahertz/react-native-typography#3]
Material Design has considerations for tall and dense scripts (perhaps Apple does too)

https://material.io/guidelines/style/typography.html

Twitter Lite has a typography component that adapts its style to the language of the text being rendered within the component. If this module were to include the material adjustments for tall and dense scripts, people could create their `AppText`/`Typography` component to automatically select the preferred text weight/size/line-height for a given language.

**Comment by hectahertz** [comment]
Thanks for the issue Nicolas!

I started working on it for Material Design, as the spec is quite clear 😄
