### ISSUE TITLE
Blank screen on Android app caused by Invalid prop 'letterSpacing' of type 'boolean'

### ISSUE THREAD

**Issue by ldevalliere** [hectahertz/react-native-typography#5]
The `false` in letterSpacing causes a style error to occur on Android and therefore the entire app fails to load. I think it is coming from here: https://github.com/hectahertz/react-native-typography/blob/master/src/collections/human.js#L20

![screenshot_20171205-135451](https://user-images.githubusercontent.com/1944278/33632976-24020eda-d9c4-11e7-970a-996fd79025d7.png)

**Comment by hectahertz** [comment]
Fixed on https://github.com/hectahertz/react-native-typography/pull/6 👏🏻
