### ISSUE TITLE
Consider including Platform styles on same Text component

### ISSUE THREAD

**Issue by zachgibson** [hectahertz/react-native-typography#9]
Have you considered being able to have one `Text` component with arbitrary iOS *and* Android styles?

Something like:
```JSX
<Text style={[human.largeTitle, material.display2]}>Hello Typography!</Text>
```

Then pick the style based on `Platform`.

**Comment by hectahertz** [comment]
Hi Zach!

I think that the React Native way of branching the code per platform is already enough for this as it is, for example, that case could be easily covered with:

```JSX
<Text style={Platform.select({ios: human.largeTitle, android: material.display2})}>
  Hello Typography!
</Text>
```

I can see different projects having different needs here and I can't come up with a use case that is gonna be so common to be worth abstracting in the library, and not in the projects.

Also, this part of the FAQ is kind of related: https://github.com/hectahertz/react-native-typography#why-is-this-library-exporting-stylesheets-and-objects-instead-of-components

Thanks for your idea 👍🏻, it's always worth to give these things a second thought!

**Comment by zachgibson** [comment]
Yeah the abstraction I was getting at is confusing I think. Agreed with you on this one!
